# Generated by Django 4.2.3 on 2023-09-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.BooleanField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
